### ISSUE TITLE
4.0.0 At a quick glance, this will need:

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/openslide-feedstock#22]
At a quick glance, this will need:

- A new dependency on [libdicom](https://github.com/ImagingDataCommons/libdicom), which will need to be packaged
- Updates for the switch from Autotools to Meson
- An updated `license_file`
- Dependency rebuilds due to the soname bump

_Originally posted by @bgilbert in https://github.com/conda-forge/openslide-feedstock/issues/20#issuecomment-1781623442_

**Comment by kaczmarj** [comment]
@hmaarrfk - i made a pr to add libdicom to conda-forge https://github.com/conda-forge/staged-recipes/pull/24674

**Comment by hmaarrfk** [comment]
Feel free to make a PR here when you build up 4.0.0
